"""add stocks table

Revision ID: 24777697e50a
Revises: 25cd5dee7dbe
Create Date: 2023-01-24 10:49:21.412410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24777697e50a'
down_revision = '25cd5dee7dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=False),
    sa.Column('number_of_shares', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
